# Manifiesto para el frontend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reps-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reps-frontend
  template:
    metadata:
      labels:
        app: reps-frontend
    spec:
      containers:
      - name: reps-frontend
        image: <tu_usuario_dockerhub>/reps-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: reps-frontend-service
spec:
  type: ClusterIP
  selector:
    app: reps-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
